### ISSUE TITLE
Getting unit test errors even though quiz answer is fine

### ISSUE THREAD

**Issue by papanugget** [udacity/FEF-Quiz-Ember-Dynamic-Data-P2#4]
Getting an error code for test #2 - Cookies Route: It's model hook works.
```Died on test #1     at testWrapper (http://localhost:4200/assets/test-support.js:6620:11)
    at test (http://localhost:4200/assets/test-support.js:6634:39)
    at Module.callback (http://localhost:4200/assets/tests.js:22:24)
    at Module.exports (http://localhost:4200/assets/vendor.js:92:34)
    at Module.build (http://localhost:4200/assets/vendor.js:142:10)
    at findModule (http://localhost:4200/assets/vendor.js:190:9)
    at requireModule (http://localhost:4200/assets/vendor.js:177:12): Cannot read property 'resolveIndex' of undefined```

No idea how to fix this currently.  The frustrating part is my code works and the the other tests pass.  If anyone has any ideas I'd be all ears.

**Comment by hbkwong** [comment]
Hey papanugget, are you still seeing errors? Feel free to reopen if so
